// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULKDgba-_lYMcpAGyvXLSJWFGvsiaKNE',
    appId: '1:809320246000:web:8ed7aed97c1873c9c8b035',
    messagingSenderId: '809320246000',
    projectId: 'playstore-2925d',
    authDomain: 'playstore-2925d.firebaseapp.com',
    storageBucket: 'playstore-2925d.appspot.com',
    measurementId: 'G-H86DVCVYJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4hVtcc5umS5lDI7088MeMqhj10y4Pk7Y',
    appId: '1:809320246000:android:9da919965ab7df0ac8b035',
    messagingSenderId: '809320246000',
    projectId: 'playstore-2925d',
    storageBucket: 'playstore-2925d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfSDm4IF9W9cNcDKve9-Ki0f3VH92FrY',
    appId: '1:809320246000:ios:e9f6a021c65c2c78c8b035',
    messagingSenderId: '809320246000',
    projectId: 'playstore-2925d',
    storageBucket: 'playstore-2925d.appspot.com',
    iosBundleId: 'com.boukouch.wallpaperworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfSDm4IF9W9cNcDKve9-Ki0f3VH92FrY',
    appId: '1:809320246000:ios:e9f6a021c65c2c78c8b035',
    messagingSenderId: '809320246000',
    projectId: 'playstore-2925d',
    storageBucket: 'playstore-2925d.appspot.com',
    iosBundleId: 'com.boukouch.wallpaperworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDULKDgba-_lYMcpAGyvXLSJWFGvsiaKNE',
    appId: '1:809320246000:web:1decc302b1aba4bcc8b035',
    messagingSenderId: '809320246000',
    projectId: 'playstore-2925d',
    authDomain: 'playstore-2925d.firebaseapp.com',
    storageBucket: 'playstore-2925d.appspot.com',
    measurementId: 'G-0LLZYBNBX8',
  );
}
